### ISSUE TITLE
Size of palette

### ISSUE THREAD

**Issue by schriftgestalt** [danielgamage/SelectionPalette#3]
can you try to make the palette a bit smaller. For people with smaller screens it needs to much space. And maybe remove some of the elements that are better off handled by keyboard shortcuts.

**Comment by danielgamage** [comment]
I agree that the top row commands are better-suited as keyboard shortcuts.
- Continue selection: `⌘⌥}`
- Undo selection: `⌘⌥{`
- Grow selection: `⌘⌥+`
- Shrink selection: `⌘⌥-`

After fudging around with different options, these are my thoughts for the most intuitive (**and not already occupied**) keyboard shortcuts. Do you see any conflicts? I put the menu commands below the other selection commands in the `Edit` Menu.

![screen shot 2016-10-13 at 3 37 32 pm](https://cloud.githubusercontent.com/assets/1642599/19364168/1612ea40-915b-11e6-83f9-c4014d95953a.png)

![screen shot 2016-10-13 at 4 01 59 pm](https://cloud.githubusercontent.com/assets/1642599/19365075/f449a184-915e-11e6-87dd-3c0261d85b5f.png)

This is where I'm at currently. Is this what you were thinking @schriftgestalt ?

**Comment by schriftgestalt** [comment]
add a separator above the menu commands or put it in a submenu to make it more clear where they come from.

And you can still push the palette together a few pixels ;)

**Comment by danielgamage** [comment]
Fixed. If you find the palette is still too tall, I'll probably have to find some other layout mechanism (maybe a scrolling table view or something). It went from 216px to 145px, though. I have an 11" monitor, and generally I've just been keeping this palette collapsed until I need it.
