### ISSUE TITLE
Tooltip for components

### ISSUE THREAD

**Issue by Mark2Mark** [danielgamage/SelectionPalette#9]
Nice Plugin, very useful, thanks for making it.

One super tiny little thing: the tooltip for the components row seems to be a copy of the anchors row. It should be »Add/Subtract/Select **Components**« as far as I understand it. :)

Not a big deal though, just a cosmetic thing 👍

**Comment by danielgamage** [comment]
Hey Mark, thanks for letting me know! Updated.

**Comment by Mark2Mark** [comment]
Thank you, Daniel.
